/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AgentMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MARKETPLACE_FEE_PERCENT"
      | "agents"
      | "creatorAgents"
      | "hireAgent"
      | "nextAgentId"
      | "registerAgent"
      | "setTreasury"
      | "treasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentPurchased" | "AgentRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MARKETPLACE_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorAgents",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hireAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextAgentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MARKETPLACE_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hireAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextAgentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace AgentPurchasedEvent {
  export type InputTuple = [
    id: BigNumberish,
    buyer: AddressLike,
    creator: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    buyer: string,
    creator: string,
    price: bigint
  ];
  export interface OutputObject {
    id: bigint;
    buyer: string;
    creator: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    name: string,
    agentType: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    name: string,
    agentType: bigint,
    price: bigint
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    name: string;
    agentType: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): AgentMarketplace;
  waitForDeployment(): Promise<this>;

  interface: AgentMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MARKETPLACE_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        agentType: bigint;
        price: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  creatorAgents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  hireAgent: TypedContractMethod<[_agentId: BigNumberish], [void], "payable">;

  nextAgentId: TypedContractMethod<[], [bigint], "view">;

  registerAgent: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _agentType: BigNumberish,
      _price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MARKETPLACE_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        agentType: bigint;
        price: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "creatorAgents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hireAgent"
  ): TypedContractMethod<[_agentId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "nextAgentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _agentType: BigNumberish,
      _price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgentPurchased"
  ): TypedContractEvent<
    AgentPurchasedEvent.InputTuple,
    AgentPurchasedEvent.OutputTuple,
    AgentPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;

  filters: {
    "AgentPurchased(uint256,address,address,uint256)": TypedContractEvent<
      AgentPurchasedEvent.InputTuple,
      AgentPurchasedEvent.OutputTuple,
      AgentPurchasedEvent.OutputObject
    >;
    AgentPurchased: TypedContractEvent<
      AgentPurchasedEvent.InputTuple,
      AgentPurchasedEvent.OutputTuple,
      AgentPurchasedEvent.OutputObject
    >;

    "AgentRegistered(uint256,address,string,uint8,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
  };
}
